openapi: '3.0.2'
info:
  title: API Marketplace Cloud
  version: '1.0'
servers:
  - url: https://cloud.italia.it/marketplace/integration-marketplace-cloud-mepa/api/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK