openapi: '3.0.2'
info:
  title: API MEPA
  version: '1.0'
servers:
  - url: https://www.acquistinretepa.it/integration-marketplace-cloud-mepa/api/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK