openapi: '3.0.2'
info:
  title: API Marketplace Cloud
  version: '1.0'
servers:
  - url: https://cloud.italia.it/marketplace/integration-marketplace-cloud-mepa/api/v1
paths:
  /snapshot-qualified-cloud-services:
    get:
      responses:
        '200':
          description: ok
        '400':
          description: bad request
        '401':
          description: unauthorized
        '404':
          description: not found