openapi: '3.0.2'
info:
  title: API MEPA
  version: '1.0'
servers:
  - url: https://www.acquistinretepa.it/integration-marketplace-cloud-mepa/api/v1
paths:
  /qualified-cloud-services:
    post:
      responses:
        '201':
          description: created
        '400':
          description: bad request
        '401':
          description: unauthorized
        '409':
          description: conflict
          
    delete:
      responses:        
        '200':
          description: ok
        '400':
          description: bad request
        '401':
          description: unauthorized
        '404':
          description: not found

    patch: 
      responses:        
        '200':
          description: ok
        '400':
          description: bad request
        '401':
          description: unauthorized
        '404':
          description: not found
